name: $(Build.DefinitionName)-$(date:yyyyMMdd)-$(rev:r)

trigger:
  branches:
    include:
      - main
      - dev
      - feat/environments

pr:
  branches:
    include:
      - main
      - dev
      - feat/environments

stages:
  - stage: Build
    displayName: 'Build Project'
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: JavaToolInstaller@0
            displayName: 'Install JDK 21'
            inputs:
              versionSpec: '21'
              jdkSource: 'PreInstalled'

          - task: Maven@4
            displayName: 'Build with Maven'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package -DskipTests'
              publishJUnitResults: false

          - publish: $(System.DefaultWorkingDirectory)/target/todo-api.jar
            artifact: 'drop'

  - stage: DeployToDev
    displayName: 'Deploy to Dev Environment'
    dependsOn: Build
    jobs:
      - deployment: DeployDev
        displayName: 'Deploy to Dev'
        environment: 'dev-environment'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: 'drop'

                - script: echo 'Deploying to dev-environment...'

  - stage: DeployToQA
    displayName: 'Deploy to QA Environment'
    dependsOn: DeployToDev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main')

    jobs:
      - deployment: DeployQA
        displayName: 'Deploy to QA'
        environment: 'qa-environment'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: 'drop'

                - script: echo 'Deploying to qa-environment...'