name: CI/CD Pipeline for SQL Server

on:
  push:
    branches:
      - main
      - qa
      - dev
      - feat/pipeline-sql-config

  pull_request:
    branches:
      - main
      - qa
      - dev
      - feat/pipeline-sql-config

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run SQL script for database setup
        env:
          DB_HOST: todo-api.database.windows.net
          DB_NAME: TodoListDB
          DB_USER: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          
          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST \
                                     -d $DB_NAME \
                                     -U $DB_USER \
                                     -P $DB_PASSWORD \
                                     -i ./src/main/resources/data.sql

      - name: Build with Maven
        run: mvn -B package -DskipTests